Improve login page and Logo
hsnthn/Sand pull request #11
Opened 2019-12-18 13:44 UTC by FurkanSalih

2019-12-22 14:26 UTC, hsnthn approved these changes

2019-12-22 14:44 UTC, hsnthn requested changes
Let's change the application logo as well. ![photo_2019-12-22_15-43-15](https://user-images.githubusercontent.com/1161997/71323295-cfb91700-24d1-11ea-96e8-8937b0ceb356.jpg)

2019-12-28 10:26 UTC, FurkanSalih commented
Done

2020-01-02 21:22 UTC, hsnthn approved these changes

2020-01-02 21:23 UTC, merged