Update conversation profile
hsnthn/Sand pull request #13
Opened 2020-01-12 04:06 UTC by hsnthn

2020-01-13 19:42 UTC, FurkanSalih requested changes

2020-01-13 19:42 UTC, FurkanSalih commented on src/main/java/eu/siacs/conversations/ui/ConversationsActivity.java
> +                        byte[] bitmapdata = conversation.getContact().getAvatar().getImageAsBytes();
System is raising an error when I try to enter a conversation group that has custom group photo. I think problem is accessing to group photo.
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: eu.siacs.conversations, PID: 4974
    java.lang.NullPointerException: Attempt to invoke virtual method 'byte[] java.lang.String.getBytes()' on a null object reference
        at android.util.Base64.decode(Base64.java:118)
        at eu.siacs.conversations.xmpp.pep.Avatar.getImageAsBytes(Avatar.java:22)
        at eu.siacs.conversations.ui.ConversationsActivity.invalidateActionBarTitle(ConversationsActivity.java:692)
        at eu.siacs.conversations.ui.ConversationsActivity.lambda$eJR_garZ1GbgPdNo7-H9kDKWyMM(Unknown Source:0)
        at eu.siacs.conversations.ui.-$$Lambda$ConversationsActivity$eJR_garZ1GbgPdNo7-H9kDKWyMM.onBackStackChanged(Unknown Source:2)
        at android.app.FragmentManagerImpl.reportBackStackChanged(FragmentManager.java:2512)
        at android.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2234)
        at android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2166)
        at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2067)
        at android.app.FragmentManagerImpl$1.run(FragmentManager.java:738)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:6878)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)
```

2020-01-15 23:40 UTC, hsnthn commented on src/main/java/eu/siacs/conversations/ui/ConversationsActivity.java
> +                        byte[] bitmapdata = conversation.getContact().getAvatar().getImageAsBytes();
@FurkanSalih fixed

2020-01-20 17:27 UTC, FurkanSalih approved these changes

2020-01-20 17:28 UTC, merged